name: Main CI/CD Workflow

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [synchronize, opened]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup project tools
        uses: ./.github/actions/setup-tools
        with:
          pnpm-version: ${{ vars.PNPM_VERSION }}
          node-vesion: ${{ vars.NODE_VERSION }}
      - name: Run linter
        run: pnpm biome check

  check-types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup project tools
        uses: ./.github/actions/setup-tools
        with:
          pnpm-version: ${{ vars.PNPM_VERSION }}
          node-vesion: ${{ vars.NODE_VERSION }}
      - name: Run type checker
        run: pnpm check-types

  test:
    needs: [lint, check-types]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup project tools
        uses: ./.github/actions/setup-tools
        with:
          pnpm-version: ${{ vars.PNPM_VERSION }}
          node-vesion: ${{ vars.NODE_VERSION }}
      - name: Run tests
        run: pnpm test
